### PR TITLE
Add, improve and declare typings

### PR DESCRIPTION
**Pull request by kriogenia**
Hi, I started using this package on a project we started at my workplace. We are using Typescript so when I imported this package it gave me some errors as it didn't have typings.

So, I added the `--declaration` flag to the build command to make it also generate the typings from the .ts files and now they should be accesible to package imports. Also, package.json didn't contain the `@inrupt/solid-client-authn-node` so I added it and now it compiles without problems even on newer clones.

As I was going to make the PR I also made some interfaces to get rid of some of the `any` to improve a bit of the typings. It can be better but I think it's a starting point. I could improve a bit more on the future but at first I did what I could with the understanding I was able to get just looking at this code.

The compilation works fine, the .d.ts files generate perfectly and all the tests pass (I didn't add any new test as I only added interfaces).

Hope this PR is welcomed and a good addition to the package.

### CODE REVIEW

**Comment by jeff-zucker** [comment]
Thanks very much, I really appreciate your contribution.  I am afraid, though that the way you submitted the PR (perhaps caused by a difference in editors) makes it impossible for me to see what you have changed.  Every file in the repo is in your PR and all lines of the files are replaced.  For example the README is replaced in its entirety and I'd have to read through the whole thing to know what you changed.  If you can resubmit the PR with only the changes you are making, that would help alot.  If not, I will try to integrate your type definitions by hand.

**Comment by jeff-zucker** [comment]
P.S. Just yesterday afternoon, I was making a list of what needed to be done to my various libraries and this was one item:
  *  move older code into typescript   

So thanks for reading my mind! :-)

**Comment by kriogenia** [comment]
Oh, my bad. I don't know why everything is like that. I'll try to fix this PR or try again, don't really know why this happened as a I didn't touch a lot of those things but I'll give it another take.

**Comment by kriogenia** [comment]
Fixed. It looks like it was a conflict using WSL, using git there replacing all the line-breaks.

**Comment by jeff-zucker** [comment]
Ah, that's better.  I assumed it was some white-space related thing.  Thanks so much!  I'll be doing a major new version in the next few days (I've added some new tricks) and I'll include your additions.  What name and link would you like when I list you in the  README under  acknowledgements?

**Comment by kriogenia** [comment]
> What name and link would you like when I list you in the README under acknowledgements?
Kriogenia and my GitHub profile is nice, thank you

**Pull request merged**
